# Two line prompt:
# format = """$all$time$character"""

# One line prompt with right prompt
# format = """$directory$character"""
format = """$character$directory"""
# format = """$time$character"""
right_format = """$all"""

[character]
success_symbol= '[â¯](bold green)'
error_symbol = '[â¯](bold red)'
# success_symbol= '[îš‘_](bold green)'
vimcmd_symbol = '[â®](bold green)'
# vimcmd_symbol = '[ó°«»îš‘_](bold bright-green)'
format = '$symbol '

[time]
# disabled = false
disabled = true
format = '[âœ¦ ](bold blue)at [$time]($style) '

[git_metrics]
disabled = true
format = '(\([+$added]($added_style) )([-$deleted]($deleted_style)\) )'

[git_branch]
symbol = "ï˜ "
style = "purple"

[git_status]
style = "cyan"
format = '([$all_status$ahead_behind]($style) )'
conflicted = 'ó°•š $count '
ahead = 'ïƒ® $count '
behind ='ïƒ­ $count '
up_to_date = ""
untracked = '[ó°»­ $count](green) '
stashed = 'ï’‡ $count '
modified = '[ï“’ $count](yellow) '
staged = '[ó°”§ $count](green) '
renamed = '[ï‘š $count](magenta) '
deleted = '[î«Ÿ $count](red) '

[directory]
truncate_to_repo = false
truncation_symbol = '.../'
truncation_length = 4
read_only = "ğŸ”’"
# style = "bright-black"
style = "white"

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î˜­ "

[elm]
symbol = "î˜¬ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "ó°²’ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "
# style = "blue"

[memory_usage]
symbol = "ó°› "

[nim]
symbol = "ó°†¥ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ó°— "

[python]
symbol = "îˆµ "

[spack]
symbol = "ğŸ…¢ "

[rust]
symbol = "ó±˜— "

[zig]
symbol = "îš© "
